### ISSUE TITLE
Failed in the ios building

### ISSUE THREAD

**Issue by SaeedNoshadi89** [KhubaibKhan4/News-KMP#1]
I want to run the app on the iOS simulator but the building has failed. 

The following build commands failed:
	PhaseScriptExecution Run\ Script /Users/macmini/Documents/kmmProjects/News-KMP/build/ios/iosApp.build/Debug-iphonesimulator/iosApp.build/Script-A9D80A052AAB5CDE006C8738.sh (in target 'iosApp' from project 'iosApp')
(1 failure)
warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'iosApp' from project 'iosApp')
warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'iosApp' from project 'iosApp')

**Comment by KhubaibKhan4** [comment]
Basically, to Run the iOS version, you need to open the iOS Module inside the Xbox and then try to run.
